export const FETCH_QUIZES_START = 'FETCH_QUIZES_START';
export const FETCH_QUIZ_START = 'FETCH_QUIZ_START';
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS';
export const FETCH_QUIZ_ERROR = 'FETCH_QUIZ_ERROR';
export const FETCH_QUIZES_SUCCESS = 'FETCH_QUIZES_SUCCESS';
export const FETCH_QUIZES_ERROR = 'FETCH_QUIZES_ERROR';

export const RETRY_QUIZ = 'RETRY_QUIZ';
export const SET_ANSWER_STATE = 'SET_ANSWER_STATE';
export const FINISH_QUIZ = 'FINISH_QUIZ';
export const SET_ACTIVE_QUESTION = 'SET_ACTIVE_QUESTION';

export const CREATE_QUESTION = 'CREATE_QUESTION';
export const RESET_QUIZ = 'RESET_QUIZ';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
